### ISSUE TITLE
cuda out of memory running on dailymail/cnn / attribute error  running on cbtne

### ISSUE THREAD

**Issue by Xuweijia-buaa** [mingdachen/gated-attention-reader#4]
when I running on dataset dailymail/cnn, occur a problem saying that:" cuda runtime error (2) : out of memory at /py/conda-bld/pytorch_1493677666423/work/torch/lib/THC/generic/THCStorage.cu:66"

I use one gpu with 12G storage, I want to now what device you run on those two dataset? Or what  can I do to optimize the operation?

**Comment by Xuweijia-buaa** [comment]
and when start training on cbtne dataset(I set the same hyper-parameters as the paper),I got shape error saying that:

Traceback (most recent call last):忖? | 100382/108719 [05:01<00:25, 332.87it/s]
  File "main.py", line 203, in <module>| 100298/108719 [05:01<00:25, 332.71it/s]
    train(args)忖忖忖忖忖忖忖忖忖忖忖   | 97701/108719 [04:57<00:33, 328.25it/s]
  File "main.py", line 136, in train?  | 97626/108719 [04:57<00:33, 328.12it/s]
    tm, c, m_c, cl, fnames)忖忖忖忖忖   | 97549/108719 [04:57<00:34, 327.98it/s]
  File "/home/xujiawei/anaconda2/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__ 97390/108719 [04:57<00:34, 327.71it/s]
    result = self.forward(*input, **kwargs)4719/108719 [04:14<00:37, 372.16it/s]
  File "/home/xujiawei/model.py", line 123, in forward [04:14<00:37, 372.02it/s]
    feat = prepare_input(doc, qry)忖    | 94506/108719 [04:14<00:38, 371.65it/s]
  File "/home/xujiawei/utils/misc.py", line 106, in prepare_input38, 371.64it/s]
    f = np.zeros(d.shape[:2]).astype('int32')57/108719 [04:13<00:38, 371.57it/s]
  File "/home/xujiawei/anaconda2/envs/py35/lib/python3.5/site-packages/torch/autograd/variable.py", line 63, in __getattr__1525/108719 [04:09<00:46, 366.16it/s]
    raise AttributeError(name)
AttributeError: shape

I don't know how to fix it?  I really need your help.Thank you very much
